import json
import re
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "site" / "_lesson-titles-en.json"
DATA_JS = ROOT / "site" / "data.js"
OUTPUT = ROOT / "site" / "lesson-titles-i18n.ko.js"


def load_lessons():
    if SOURCE.exists():
        return json.loads(SOURCE.read_text(encoding="utf-8"))
    # Fallback: extract from data.js with Node when the cache JSON is absent.
    import subprocess
    script = (
        "const fs=require('fs');const vm=require('vm');"
        "const s={};vm.runInNewContext(fs.readFileSync('site/data.js','utf8')+';\\nthis.PHASES=PHASES;',s);"
        "const out=[];for(const p of s.PHASES){for(const l of p.lessons){"
        "const m=String(l.url||'').match(/(phases\\/[^/]+\\/[^/]+)/);"
        "out.push({path:m?m[1]:'',name:l.name,phase:p.id});}}"
        "process.stdout.write(JSON.stringify(out));"
    )
    raw = subprocess.check_output(["node", "-e", script], cwd=str(ROOT))
    return json.loads(raw.decode("utf-8"))


# Longest phrases are replaced first. Product/model names intentionally remain English.
PHRASES = {
    "Capstone: ": "캡스톤: ",
    " (Capstone)": "",
    "from Scratch": "직접 구현",
    "From Scratch": "직접 구현",
    "from scratch": "직접 구현",
    "End-to-End": "엔드투엔드",
    "What Is Machine Learning": "머신러닝이란",
    "Where It All Started": "모든 것의 시작",
    "What Actually Matters": "실제로 중요한 것",
    "Why Capable Models Still Fail": "유능한 모델도 실패하는 이유",
    "Why Agents Break": "에이전트가 실패하는 이유",
    "Why Transformers": "Transformer가 필요한 이유",
    "Why Multi-Agent": "멀티 에이전트가 필요한 이유",
    "Build Your Own": "나만의",
    "Build a Complete": "완전한",
    "Building a Complete": "완전한",
    "Building an": "",
    "Building a": "",
    "Build an": "",
    "Build a": "",
    "The Full Transformer": "완전한 Transformer",
    "The Tool Interface": "툴 인터페이스",
    "The Agent Loop": "에이전트 루프",
    "The Multi-Agent Primitive Model": "멀티 에이전트 기본 모델",
    "The Minimal Agent Workbench": "최소 에이전트 워크벤치",
    "The Workbench on a Real Repo": "실제 저장소의 워크벤치",
    "The Harness as a Library": "라이브러리형 하네스",
    "Direct Preference Optimization": "직접 선호 최적화",
    "Retrieval-Augmented Generation": "검색 증강 생성",
    "Automatic Differentiation": "자동 미분",
    "Gradient Descent Family": "경사 하강법 계열",
    "Singular Value Decomposition": "특잇값 분해",
    "Support Vector Machines": "서포트 벡터 머신",
    "Machine Learning": "머신러닝",
    "Deep Learning": "딥러닝",
    "Linear Algebra": "선형대수",
    "Linear Regression": "선형 회귀",
    "Logistic Regression": "로지스틱 회귀",
    "Decision Trees": "결정 트리",
    "Random Forests": "랜덤 포레스트",
    "Gradient Checkpointing": "그래디언트 체크포인팅",
    "Activation Recomputation": "활성값 재계산",
    "Gradient Accumulation": "그래디언트 누적",
    "Gradient Clipping": "그래디언트 클리핑",
    "Policy Gradients": "정책 그래디언트",
    "Actor-Critic": "액터-크리틱",
    "Dynamic Programming": "동적 계획법",
    "Monte Carlo Methods": "몬테카를로 방법",
    "Reward Modeling": "보상 모델링",
    "Reinforcement Learning": "강화학습",
    "Multi-Agent RL": "멀티 에이전트 RL",
    "Unsupervised Learning": "비지도학습",
    "Feature Engineering": "특성 공학",
    "Feature Selection": "특성 선택",
    "Model Evaluation": "모델 평가",
    "Hyperparameter Tuning": "하이퍼파라미터 튜닝",
    "Experiment Tracking": "실험 추적",
    "Handling Imbalanced Data": "불균형 데이터 처리",
    "Anomaly Detection": "이상 탐지",
    "Time Series Fundamentals": "시계열 기초",
    "Statistical Thinking": "통계적 사고",
    "Probability": "확률",
    "Distributions": "분포",
    "Information Theory": "정보 이론",
    "Dimensionality Reduction": "차원 축소",
    "Numerical Stability": "수치 안정성",
    "Stochastic Processes": "확률 과정",
    "Convex Optimization": "볼록 최적화",
    "Complex Numbers": "복소수",
    "Fourier Transform": "푸리에 변환",
    "Graph Theory": "그래프 이론",
    "Sampling Methods": "샘플링 방법",
    "Linear Systems": "선형 시스템",
    "Vectors, Matrices": "벡터와 행렬",
    "Matrix Transformations": "행렬 변환",
    "Eigenvalues": "고윳값",
    "Derivatives": "도함수",
    "Gradients": "그래디언트",
    "Chain Rule": "연쇄 법칙",
    "Tensor Operations": "텐서 연산",
    "Norms": "노름",
    "Distances": "거리",
    "Statistics": "통계",
    "Optimization": "최적화",
    "Multi-Layer Networks": "다층 신경망",
    "Forward Pass": "순전파",
    "Backpropagation": "역전파",
    "Activation Functions": "활성화 함수",
    "Loss Functions": "손실 함수",
    "Weight Initialization": "가중치 초기화",
    "Training Stability": "학습 안정성",
    "Learning Rate Schedules": "학습률 스케줄",
    "Neural Networks": "신경망",
    "Introduction to": "입문",
    "Image Fundamentals": "이미지 기초",
    "Image Classification": "이미지 분류",
    "Object Detection": "객체 탐지",
    "Semantic Segmentation": "의미론적 분할",
    "Instance Segmentation": "인스턴스 분할",
    "Image Generation": "이미지 생성",
    "Video Understanding": "비디오 이해",
    "Vision Transformers": "비전 Transformer",
    "Real-Time Vision": "실시간 비전",
    "Self-Supervised Vision": "자기지도 비전",
    "Open-Vocabulary Vision": "오픈 보캐뷸러리 비전",
    "Document Understanding": "문서 이해",
    "Image Retrieval": "이미지 검색",
    "Metric Learning": "메트릭 학습",
    "Keypoint Detection": "키포인트 탐지",
    "Pose Estimation": "자세 추정",
    "Diffusion Transformers": "Diffusion Transformer",
    "Rectified Flow": "Rectified Flow",
    "Vision-Language Models": "비전-언어 모델",
    "Monocular Depth": "단안 깊이",
    "Geometry Estimation": "기하 추정",
    "Multi-Object Tracking": "다중 객체 추적",
    "Video Memory": "비디오 메모리",
    "World Models": "월드 모델",
    "Video Diffusion": "비디오 Diffusion",
    "Text Processing": "텍스트 처리",
    "Text Representation": "텍스트 표현",
    "Word Embeddings": "단어 임베딩",
    "Subword Embeddings": "서브워드 임베딩",
    "Sentiment Analysis": "감성 분석",
    "Named Entity Recognition": "개체명 인식",
    "Syntactic Parsing": "구문 분석",
    "Text Classification": "텍스트 분류",
    "Sequence-to-Sequence Models": "시퀀스-투-시퀀스 모델",
    "Attention Mechanism": "어텐션 메커니즘",
    "Machine Translation": "기계 번역",
    "Text Summarization": "텍스트 요약",
    "Question Answering Systems": "질의응답 시스템",
    "Information Retrieval": "정보 검색",
    "Topic Modeling": "토픽 모델링",
    "Text Generation": "텍스트 생성",
    "Rule-Based to Neural": "규칙 기반에서 신경망까지",
    "Multilingual NLP": "다국어 NLP",
    "Subword Tokenization": "서브워드 토큰화",
    "Structured Outputs": "구조화 출력",
    "Structured Output": "구조화 출력",
    "Constrained Decoding": "제약 디코딩",
    "Textual Entailment": "텍스트 함의",
    "Embedding Models Deep Dive": "임베딩 모델 심화",
    "Chunking Strategies": "청킹 전략",
    "Coreference Resolution": "상호참조 해결",
    "Entity Linking": "엔티티 연결",
    "Disambiguation": "중의성 해소",
    "Relation Extraction": "관계 추출",
    "Knowledge Graph Construction": "지식 그래프 구축",
    "Long-Context Evaluation": "장문 컨텍스트 평가",
    "Dialogue State Tracking": "대화 상태 추적",
    "Audio Fundamentals": "오디오 기초",
    "Audio Features": "오디오 특성",
    "Audio Classification": "오디오 분류",
    "Speech Recognition": "음성 인식",
    "Speaker Recognition": "화자 인식",
    "Voice Cloning": "음성 복제",
    "Voice Conversion": "음성 변환",
    "Music Generation": "음악 생성",
    "Audio Generation": "오디오 생성",
    "Audio-Language Models": "오디오-언어 모델",
    "Real-Time Audio Processing": "실시간 오디오 처리",
    "Voice Assistant Pipeline": "음성 비서 파이프라인",
    "Neural Audio Codecs": "신경망 오디오 코덱",
    "Voice Activity Detection": "음성 활동 탐지",
    "Turn-Taking": "턴테이킹",
    "Streaming Speech-to-Speech": "스트리밍 음성-음성 변환",
    "Voice Anti-Spoofing": "음성 스푸핑 방지",
    "Audio Watermarking": "오디오 워터마킹",
    "Audio Evaluation": "오디오 평가",
    "Self-Attention": "셀프 어텐션",
    "Multi-Head Attention": "멀티헤드 어텐션",
    "Positional Encoding": "위치 인코딩",
    "Masked Language Modeling": "마스크 언어 모델링",
    "Causal Language Modeling": "인과적 언어 모델링",
    "Encoder-Decoder Models": "인코더-디코더 모델",
    "Mixture of Experts": "전문가 혼합",
    "Inference Optimization": "추론 최적화",
    "Scaling Laws": "스케일링 법칙",
    "Attention Variants": "어텐션 변형",
    "Speculative Decoding": "추측 디코딩",
    "Generative Models": "생성 모델",
    "Autoencoders": "오토인코더",
    "Generator vs Discriminator": "생성자 대 판별자",
    "Conditional GANs": "조건부 GAN",
    "Diffusion Models": "Diffusion 모델",
    "Latent Diffusion": "잠재 Diffusion",
    "Flow Matching": "플로 매칭",
    "Visual Autoregressive Modeling": "비주얼 자기회귀 모델링",
    "Next-Scale Prediction": "다음 스케일 예측",
    "Pre-Training": "사전학습",
    "Distributed Training": "분산 학습",
    "Instruction Tuning": "인스트럭션 튜닝",
    "Constitutional AI": "헌법적 AI",
    "Self-Improvement": "자기 개선",
    "Open Models": "오픈 모델",
    "Architecture Walkthroughs": "아키텍처 해설",
    "Architecture Walkthrough": "아키텍처 해설",
    "Differential Attention": "차등 어텐션",
    "Native Sparse Attention": "네이티브 희소 어텐션",
    "Multi-Token Prediction": "멀티 토큰 예측",
    "Parallelism": "병렬화",
    "Async and Hogwild! Inference": "비동기 및 Hogwild! 추론",
    "Prompt Engineering": "프롬프트 엔지니어링",
    "Techniques": "기법",
    "Patterns": "패턴",
    "Vector Representations": "벡터 표현",
    "Context Engineering": "컨텍스트 엔지니어링",
    "Advanced RAG": "고급 RAG",
    "Fine-Tuning": "파인튜닝",
    "Function Calling": "함수 호출",
    "Tool Use": "툴 사용",
    "Rate Limiting": "요청 속도 제한",
    "Guardrails": "가드레일",
    "Production LLM App": "프로덕션 LLM 앱",
    "Model Context Protocol": "모델 컨텍스트 프로토콜",
    "Prompt Caching": "프롬프트 캐싱",
    "Context Caching": "컨텍스트 캐싱",
    "Agent State Machines": "에이전트 상태 머신",
    "Agent Framework Tradeoffs": "에이전트 프레임워크 트레이드오프",
    "Patch-Token Primitive": "패치 토큰 기본 단위",
    "Contrastive Vision-Language Pretraining": "대조학습 기반 비전-언어 사전학습",
    "Modality Bridge": "모달리티 브리지",
    "Gated Cross-Attention": "게이트 크로스 어텐션",
    "Visual Instruction Tuning": "비주얼 인스트럭션 튜닝",
    "Any-Resolution Vision": "가변 해상도 비전",
    "Open-Weight VLM Recipes": "오픈 웨이트 VLM 레시피",
    "Native Multimodal Pretraining": "네이티브 멀티모달 사전학습",
    "Early-Fusion Token-Only": "조기 융합 토큰 전용 모델",
    "Next-Token Prediction for Generation": "생성용 다음 토큰 예측",
    "Discrete-Diffusion Unified": "이산 Diffusion 통합",
    "Decoupled Encoders": "분리형 인코더",
    "Any-to-Any Streaming": "Any-to-Any 스트리밍",
    "Temporal Grounding": "시간적 그라운딩",
    "Long-Video at Million-Token Context": "백만 토큰 컨텍스트 장편 비디오",
    "Omni Models": "옴니 모델",
    "Embodied VLAs": "체화형 VLA",
    "Document and Diagram Understanding": "문서 및 다이어그램 이해",
    "Vision-Native Document RAG": "비전 네이티브 문서 RAG",
    "Multimodal RAG": "멀티모달 RAG",
    "Cross-Modal Retrieval": "교차 모달 검색",
    "Multimodal Agents": "멀티모달 에이전트",
    "Computer-Use": "컴퓨터 사용",
    "Tool Schema Design": "툴 스키마 설계",
    "Tool Calls": "툴 호출",
    "Tool Contracts": "툴 계약",
    "MCP Fundamentals": "MCP 기초",
    "MCP Transports": "MCP 전송",
    "MCP Resources": "MCP 리소스",
    "MCP Model Input": "MCP 모델 입력",
    "MCP Tasks Extension": "MCP 작업 확장",
    "MCP Apps": "MCP 앱",
    "MCP Security": "MCP 보안",
    "MCP Authorization": "MCP 권한 부여",
    "MCP Gateways": "MCP 게이트웨이",
    "Registry Admission": "레지스트리 승인",
    "MCP Auth in Production": "프로덕션 MCP 인증",
    "A2A Protocol": "A2A 프로토콜",
    "LLM Routing Layer": "LLM 라우팅 계층",
    "Agent Skills": "에이전트 스킬",
    "Portable Contract": "이식 가능한 계약",
    "Runtime Boundary": "런타임 경계",
    "Stateless Tool Ecosystem": "상태 비저장 툴 생태계",
    "Skill Discovery": "스킬 탐색",
    "Progressive Disclosure": "점진적 공개",
    "Skill Invocation": "스킬 호출",
    "Skill Permissions": "스킬 권한",
    "Sandboxes": "샌드박스",
    "Skill Evals": "스킬 평가",
    "Packaging": "패키징",
    "Portability": "이식성",
    "Flow Control": "흐름 제어",
    "Supply Chain": "공급망",
    "Conformance Engineering": "적합성 엔지니어링",
    "Verbal Reinforcement Learning": "언어적 강화학습",
    "Tree of Thoughts": "사고 트리",
    "Lifelong Learning": "평생학습",
    "Evolutionary Search": "진화 탐색",
    "Workflow Patterns": "워크플로 패턴",
    "Stateful Graph Orchestration": "상태 기반 그래프 오케스트레이션",
    "The Actor Model for Agents": "에이전트 액터 모델",
    "Role-Based Agent Teams": "역할 기반 에이전트 팀",
    "Production Agent Runtimes": "프로덕션 에이전트 런타임",
    "Computer Use": "컴퓨터 사용",
    "Voice Agents": "음성 에이전트",
    "Semantic Conventions": "시맨틱 규약",
    "Agent Observability": "에이전트 관측성",
    "Multi-Agent Debate": "멀티 에이전트 토론",
    "Orchestration Patterns": "오케스트레이션 패턴",
    "Production Runtimes": "프로덕션 런타임",
    "Eval-Driven Agent Development": "평가 주도 에이전트 개발",
    "Agent Workbench": "에이전트 워크벤치",
    "Agent Instructions as Executable Constraints": "실행 가능한 제약으로서의 에이전트 지침",
    "Repo Memory": "저장소 메모리",
    "Durable State": "영속 상태",
    "Initialization Scripts for Agents": "에이전트 초기화 스크립트",
    "Scope Contracts": "범위 계약",
    "Task Boundaries": "작업 경계",
    "Runtime Feedback Loops": "런타임 피드백 루프",
    "Verification Gates": "검증 게이트",
    "Reviewer Agent": "리뷰어 에이전트",
    "Multi-Session Handoff": "다중 세션 인계",
    "Reusable Agent Workbench Pack": "재사용 가능한 에이전트 워크벤치 팩",
    "Long-Horizon Agents": "장기 실행 에이전트",
    "Self-Taught Reasoning": "자기학습 추론",
    "Evolutionary Coding Agents": "진화형 코딩 에이전트",
    "Self-Modifying Agents": "자기 수정 에이전트",
    "Workshop-Level Research": "워크숍 수준 연구",
    "Automated Alignment Research": "자동화 정렬 연구",
    "Recursive Self-Improvement": "재귀적 자기 개선",
    "Bounded Self-Improvement Designs": "제한형 자기 개선 설계",
    "Autonomous Coding Agent Landscape": "자율 코딩 에이전트 생태계",
    "Permission Modes for Autonomous Agents": "자율 에이전트 권한 모드",
    "Browser Agents": "브라우저 에이전트",
    "Indirect Prompt Injection": "간접 프롬프트 인젝션",
    "Durable Execution": "영속 실행",
    "Long-Running Agents": "장기 실행 에이전트",
    "Action Budgets": "행동 예산",
    "Iteration Caps": "반복 상한",
    "Cost Governors": "비용 제어",
    "Kill Switches": "킬 스위치",
    "Circuit Breakers": "서킷 브레이커",
    "Canary Tokens": "카나리 토큰",
    "Checkpoints and Rollback": "체크포인트와 롤백",
    "Rule Overrides": "규칙 재정의",
    "Input/Output Classification": "입출력 분류",
    "External Evaluation": "외부 평가",
    "Societal-Scale Risk": "사회 규모 위험",
    "Communication Protocols": "통신 프로토콜",
    "Hierarchical Architecture": "계층형 아키텍처",
    "Decomposition Drift": "분해 드리프트",
    "Society of Mind": "마음의 사회",
    "Role Specialization": "역할 전문화",
    "Parallel Swarm": "병렬 스웜",
    "Networked Architectures": "네트워크형 아키텍처",
    "Group Chat": "그룹 채팅",
    "Speaker Selection": "발화자 선택",
    "Handoffs": "핸드오프",
    "Shared Memory": "공유 메모리",
    "Blackboard Patterns": "블랙보드 패턴",
    "Byzantine Fault Tolerance": "비잔틴 장애 허용",
    "Self-Consistency": "자기 일관성",
    "Debate Topology": "토론 토폴로지",
    "Negotiation": "협상",
    "Bargaining": "교섭",
    "Generative Agents": "생성형 에이전트",
    "Emergent Simulation": "창발적 시뮬레이션",
    "Theory of Mind": "마음 이론",
    "Emergent Coordination": "창발적 조정",
    "Swarm Optimization": "군집 최적화",
    "Agent Economies": "에이전트 경제",
    "Token Incentives": "토큰 인센티브",
    "Reputation": "평판",
    "Production Scaling": "프로덕션 확장",
    "Coordination Benchmarks": "조정 벤치마크",
    "Case Studies": "사례 연구",
    "State of the Art": "최신 기술",
    "Managed LLM Platforms": "관리형 LLM 플랫폼",
    "Inference Platform Economics": "추론 플랫폼 경제성",
    "GPU Autoscaling": "GPU 오토스케일링",
    "Serving Engine Internals": "서빙 엔진 내부 구조",
    "Speculative Decoding in Production": "프로덕션 추측 디코딩",
    "Prefix-Cache Serving": "프리픽스 캐시 서빙",
    "Hardware-Specialized Inference Compilation": "하드웨어 특화 추론 컴파일",
    "Inference Metrics": "추론 지표",
    "Production Quantization": "프로덕션 양자화",
    "Cold Start Mitigation": "콜드 스타트 완화",
    "Multi-Region LLM Serving": "다중 리전 LLM 서빙",
    "Edge Inference": "엣지 추론",
    "LLM Observability Stack Selection": "LLM 관측성 스택 선택",
    "Semantic Caching Economics": "시맨틱 캐싱 경제성",
    "Batch APIs": "배치 API",
    "Model Routing": "모델 라우팅",
    "Cost-Reduction Primitive": "비용 절감 기본 수단",
    "Disaggregated Prefill/Decode": "분리형 프리필/디코드",
    "Production Serving Stack": "프로덕션 서빙 스택",
    "Cache-Aware Routing": "캐시 인식 라우팅",
    "AI Gateways": "AI 게이트웨이",
    "Progressive Deployment": "점진적 배포",
    "Load Testing": "부하 테스트",
    "Multi-Agent Incident Response": "멀티 에이전트 사고 대응",
    "Chaos Engineering": "카오스 엔지니어링",
    "Security": "보안",
    "Secrets": "시크릿",
    "PII Scrubbing": "PII 제거",
    "Audit Logs": "감사 로그",
    "Compliance": "컴플라이언스",
    "Unit Economics": "단위 경제성",
    "Multi-Tenant Attribution": "멀티테넌트 비용 귀속",
    "Self-Hosted Serving Selection": "셀프 호스팅 서빙 선택",
    "Instruction-Following as Alignment Signal": "정렬 신호로서의 지시 이행",
    "Reward Hacking": "보상 해킹",
    "Goodhart's Law": "굿하트의 법칙",
    "Sycophancy as RLHF Amplification": "RLHF가 증폭하는 아첨",
    "Mesa-Optimization": "메사 최적화",
    "Deceptive Alignment": "기만적 정렬",
    "Sleeper Agents": "슬리퍼 에이전트",
    "Persistent Deception": "지속적 기만",
    "In-Context Scheming in Frontier Models": "프런티어 모델의 컨텍스트 내 책략",
    "Alignment Faking": "정렬 위장",
    "Scalable Oversight": "확장 가능한 감독",
    "Weak-to-Strong": "약한 모델에서 강한 모델로",
    "Automated Attacks": "자동화 공격",
    "Many-Shot Jailbreaking": "다수 예시 탈옥",
    "Visual Jailbreaks": "시각적 탈옥",
    "Red-Team Tooling": "레드팀 도구",
    "Dual-Use Capability Evaluation": "이중 용도 역량 평가",
    "Frontier Safety Frameworks": "프런티어 안전 프레임워크",
    "Model Welfare Research": "모델 복지 연구",
    "Representational Harm": "표현적 피해",
    "Fairness Criteria": "공정성 기준",
    "Differential Privacy": "차등 프라이버시",
    "Regulatory Frameworks": "규제 프레임워크",
    "Model, System": "모델·시스템",
    "Dataset Cards": "데이터셋 카드",
    "Data Provenance": "데이터 출처",
    "Training-Data Governance": "학습 데이터 거버넌스",
    "Alignment Research Ecosystem": "정렬 연구 생태계",
    "Moderation Systems": "콘텐츠 조정 시스템",
    "Dual-Use Risk": "이중 용도 위험",
    "Terminal-Native Coding Agent": "터미널 네이티브 코딩 에이전트",
    "RAG over Codebase": "코드베이스 RAG",
    "Real-Time Voice Assistant": "실시간 음성 비서",
    "Multimodal Document QA": "멀티모달 문서 QA",
    "Autonomous Research Agent": "자율 연구 에이전트",
    "DevOps Troubleshooting Agent": "DevOps 문제 해결 에이전트",
    "Fine-Tuning Pipeline": "파인튜닝 파이프라인",
    "Production RAG Chatbot": "프로덕션 RAG 챗봇",
    "Code Migration Agent": "코드 마이그레이션 에이전트",
    "Multi-Agent Software Engineering Team": "멀티 에이전트 소프트웨어 엔지니어링 팀",
    "LLM Observability": "LLM 관측성",
    "Eval Dashboard": "평가 대시보드",
    "Video Understanding Pipeline": "비디오 이해 파이프라인",
    "MCP Server": "MCP 서버",
    "Inference Server": "추론 서버",
    "Constitutional Safety Harness": "헌법적 안전 하네스",
    "Red-Team Range": "레드팀 실습장",
    "Autonomous Agent": "자율 에이전트",
    "Personal AI Tutor": "개인 AI 튜터",
    "Agent Harness Loop Contract": "에이전트 하네스 루프 계약",
    "Tool Registry": "툴 레지스트리",
    "Schema Validation": "스키마 검증",
    "Function Call Dispatcher": "함수 호출 디스패처",
    "Plan-Execute Control Flow": "계획-실행 제어 흐름",
    "Observation Budget": "관찰 예산",
    "Sandbox Runner": "샌드박스 러너",
    "Path Jail": "경로 격리",
    "Eval Harness": "평가 하네스",
    "Fixture Tasks": "픽스처 작업",
    "Observability": "관측성",
    "End-to-End Coding Agent on the Harness": "하네스 기반 엔드투엔드 코딩 에이전트",
    "BPE Tokenizer": "BPE 토크나이저",
    "Tokenized Dataset": "토큰화 데이터셋",
    "Sliding Window": "슬라이딩 윈도",
    "Token and Positional Embeddings": "토큰 및 위치 임베딩",
    "Multi-Head Self-Attention": "멀티헤드 셀프 어텐션",
    "Transformer Block": "Transformer 블록",
    "GPT Model Assembly": "GPT 모델 조립",
    "Training Loop": "학습 루프",
    "Loading Pretrained Weights": "사전학습 가중치 로드",
    "Classifier Fine-Tuning": "분류기 파인튜닝",
    "Supervised Fine-Tuning": "지도 파인튜닝",
    "Full Evaluation Pipeline": "전체 평가 파이프라인",
    "Large Corpus Downloader": "대규모 말뭉치 다운로더",
    "Tokenized Corpus": "토큰화 말뭉치",
    "Linear Warmup": "선형 워밍업",
    "Mixed Precision": "혼합 정밀도",
    "Checkpoint Save and Resume": "체크포인트 저장 및 재개",
    "Distributed Data Parallel": "분산 데이터 병렬",
    "Language Model Evaluation Harness": "언어 모델 평가 하네스",
    "Hypothesis Generator": "가설 생성기",
    "Literature Retrieval": "문헌 검색",
    "Experiment Runner": "실험 러너",
    "Result Evaluator": "결과 평가기",
    "Paper Writer": "논문 작성기",
    "Critic Loop": "비평 루프",
    "Iteration Scheduler": "반복 스케줄러",
    "Research Demo": "연구 데모",
    "Vision Encoder Patches": "비전 인코더 패치",
    "Vision Transformer Encoder": "비전 Transformer 인코더",
    "Projection Layer for Modality Alignment": "모달리티 정렬용 투영 계층",
    "Cross-Attention Fusion": "크로스 어텐션 융합",
    "Vision-Language Pretraining": "비전-언어 사전학습",
    "Multimodal Evaluation": "멀티모달 평가",
    "Hybrid Retrieval": "하이브리드 검색",
    "Dense Embeddings": "밀집 임베딩",
    "Cross-Encoder Reranker": "크로스 인코더 리랭커",
    "Query Rewriting": "쿼리 재작성",
    "Answer Relevance": "답변 관련성",
    "RAG System": "RAG 시스템",
    "Task Spec Format": "작업 명세 형식",
    "Classical Metrics": "전통적 지표",
    "Code Exec Metric": "코드 실행 지표",
    "Perplexity": "퍼플렉시티",
    "Calibration": "캘리브레이션",
    "Leaderboard Aggregation": "리더보드 집계",
    "Eval Runner": "평가 러너",
    "Collective Ops": "집합 통신 연산",
    "Data Parallel DDP": "데이터 병렬 DDP",
    "Optimizer State Sharding": "옵티마이저 상태 샤딩",
    "Pipeline Parallel": "파이프라인 병렬화",
    "Bubble Analysis": "버블 분석",
    "Sharded Checkpoint": "샤딩 체크포인트",
    "Atomic Resume": "원자적 재개",
    "Jailbreak Taxonomy": "탈옥 분류 체계",
    "Prompt Injection Detector": "프롬프트 인젝션 탐지기",
    "Refusal Evaluation": "거부 응답 평가",
    "Content Classifier Integration": "콘텐츠 분류기 통합",
    "Constitutional Rules Engine": "헌법적 규칙 엔진",
    "Safety Gate": "안전 게이트",
}

WORDS = {
    "and": "및", "&": "및",
    "Fundamentals": "기초", "Intuition": "직관", "Operations": "연산",
    "Evaluation": "평가", "Metrics": "지표", "Testing": "테스트",
    "Classification": "분류", "Generation": "생성", "Architecture": "아키텍처",
    "Fine-Tuning": "파인튜닝", "Transfer Learning": "전이학습",
    "Temporal Modeling": "시간 모델링", "Point Clouds": "포인트 클라우드",
    "Edge Deployment": "엣지 배포", "Complete": "완전한",
    "Tokenization": "토큰화", "Stemming": "어간 추출", "Lemmatization": "표제어 추출",
    "Chatbots": "챗봇", "Deep Dive": "심화", "Taxonomy": "분류 체계",
    "History": "역사", "Editing": "편집", "Conditioning": "조건화",
    "States": "상태", "Actions": "행동", "Rewards": "보상",
    "Data Pipelines": "데이터 파이프라인", "Quantization": "양자화",
    "Benchmarks": "벤치마크", "Caching": "캐싱",
    "Cost": "비용", "Graphs": "그래프", "Nodes": "노드",
    "Checkpoints": "체크포인트", "Routing": "라우팅", "Discovery": "탐색",
    "Resources": "리소스", "Prompts": "프롬프트", "Requests": "요청",
    "Migration": "마이그레이션", "Scope": "범위", "Tasks": "작업",
    "Durable Work": "영속 작업", "Protocol": "프로토콜", "Metadata": "메타데이터",
    "State": "상태", "Versioning": "버전 관리", "Evidence": "증거",
    "Reliability": "신뢰성", "Cancellation": "취소",
    "Drift": "드리프트", "Rollback": "롤백", "Trust": "신뢰",
    "Memory": "메모리", "Planning": "계획", "Execution": "실행",
    "Roles": "역할", "Processes": "프로세스", "Tracing": "트레이싱",
    "Collaboration": "협업", "Queue": "큐", "Event": "이벤트",
    "Constraints": "제약", "Feedback": "피드백", "System": "시스템",
    "Outcome": "성과", "Output": "출력", "Workflow": "워크플로",
    "Assumptions": "가정", "Risk": "위험", "Specifications": "명세",
    "Success Metrics": "성공 지표", "Result": "결과", "Prototype": "프로토타입",
    "Pilot": "파일럿", "Production": "프로덕션", "Ownership": "소유권",
    "Retirement": "종료", "Capability": "역량", "Alignment": "정렬",
    "Reasoning": "추론", "Research": "연구", "Scaling": "확장",
    "Policy": "정책", "Time Horizons": "시간 지평", "Speech Acts": "화행",
    "Coordination": "조정", "Consensus": "합의", "Voting": "투표",
    "Queues": "큐", "Durability": "내구성", "Failure Modes": "실패 모드",
    "Groupthink": "집단사고", "Monoculture": "단일문화",
    "Serving": "서빙", "Economics": "경제성", "Continuous Batching": "연속 배칭",
    "Chunked Prefill": "청크 프리필", "KV Reuse": "KV 재사용",
    "Locality": "지역성", "Deployment": "배포", "Features": "기능",
    "Incident Response": "사고 대응", "Governance": "거버넌스",
    "Fairness": "공정성", "Bias": "편향", "Watermarking": "워터마킹",
    "Safety": "안전", "Frameworks": "프레임워크", "Persistent": "지속적",
    "Attacks": "공격", "Cards": "카드", "Korea": "한국",
    "Downloader": "다운로더", "Dispatcher": "디스패처", "Runner": "러너",
    "Detector": "탐지기", "Integration": "통합", "Compared": "비교",
    "Calculus": "미적분", "Derivatives": "도함수", "Gradients": "그래디언트",
    "Entropy": "엔트로피", "Warmup": "워밍업", "Regularization": "정규화",
    "Optimizers": "옵티마이저", "Debugging": "디버깅", "Mini Framework": "미니 프레임워크",
}

EXACT = {
    "Dev Environment": "개발 환경 구축",
    "Git & Collaboration": "Git과 협업",
    "GPU Setup & Cloud": "GPU 설정과 클라우드",
    "APIs & Keys": "API와 키 관리",
    "Jupyter Notebooks": "주피터 노트북",
    "Python Environments": "파이썬 가상 환경",
    "Docker for AI": "AI를 위한 도커",
    "Editor Setup": "에디터 환경 설정",
    "Data Management": "데이터 관리",
    "Terminal & Shell": "터미널과 쉘 활용",
    "Linux for AI": "AI 엔지니어를 위한 리눅스",
    "Debugging & Profiling": "디버깅 및 프로파일링",
    "Linear Algebra Intuition": "선형대수 직관",
    "Vectors, Matrices & Operations": "벡터, 행렬과 연산",
    "Matrix Transformations & Eigenvalues": "행렬 변환과 고윳값",
    "Calculus for ML: Derivatives & Gradients": "머신러닝을 위한 미적분: 도함수와 그래디언트",
    "Chain Rule & Automatic Differentiation": "연쇄법칙과 자동 미분",
    "Probability & Distributions": "확률과 분포",
    "Bayes' Theorem & Statistical Thinking": "베이즈 정리와 통계적 사고",
    "Optimization: Gradient Descent Family": "최적화: 경사 하강법 계열",
    "Information Theory: Entropy, KL Divergence": "정보 이론: 엔트로피, KL 발산",
    "Dimensionality Reduction: PCA, t-SNE, UMAP": "차원 축소: PCA, t-SNE, UMAP",
    "Norms & Distances": "노름과 거리",
    "Statistics for ML": "머신러닝을 위한 통계",
    "Complex Numbers for AI": "AI를 위한 복소수",
    "The Fourier Transform": "푸리에 변환",
    "Graph Theory for ML": "머신러닝을 위한 그래프 이론",
    "The Perceptron: Where It All Started": "퍼셉트론: 모든 것의 시작",
    "Multi-Layer Networks & Forward Pass": "다층 신경망과 순전파",
    "Backpropagation from Scratch": "역전파 직접 구현",
    "Activation Functions: ReLU, Sigmoid, GELU & Why": "활성화 함수: ReLU, Sigmoid, GELU와 그 이유",
    "Loss Functions: MSE, Cross-Entropy, Contrastive": "손실 함수: MSE, Cross-Entropy, Contrastive",
    "Optimizers: SGD, Momentum, Adam, AdamW": "옵티마이저: SGD, Momentum, Adam, AdamW",
    "Regularization: Dropout, Weight Decay, BatchNorm": "정규화: Dropout, Weight Decay, BatchNorm",
    "Weight Initialization & Training Stability": "가중치 초기화와 학습 안정성",
    "Learning Rate Schedules & Warmup": "학습률 스케줄과 워밍업",
    "Build Your Own Mini Framework": "나만의 미니 프레임워크 만들기",
    "Introduction to PyTorch": "PyTorch 입문",
    "Introduction to JAX": "JAX 입문",
    "Debugging Neural Networks": "신경망 디버깅",
    "Convolutions from Scratch": "합성곱 직접 구현",
    "CNNs: LeNet to ResNet": "CNN: LeNet부터 ResNet까지",
    "Build a Complete Vision Pipeline": "캡스톤: 완전한 비전 파이프라인",
    "Build a Voice Assistant Pipeline": "캡스톤: 음성 비서 파이프라인",
    "Build a Transformer from Scratch": "캡스톤: Transformer 직접 구현",
    "Building a Complete LLM Pipeline": "캡스톤: 완전한 LLM 파이프라인",
    "Multimodal Agents and Computer-Use (Capstone)": "캡스톤: 멀티모달 에이전트와 컴퓨터 사용",
    "Hybrid Retrieval with BM25 and Dense Embeddings": "BM25와 밀집 임베딩 하이브리드 검색",
    "A/B Testing LLM Features — GrowthBook and Statsig": "LLM 기능 A/B 테스트 — GrowthBook과 Statsig",
    "Linear Regression from Scratch": "선형 회귀 직접 구현",
    "Logistic Regression & Classification": "로지스틱 회귀와 분류",
    "Decision Trees & Random Forests": "결정 트리와 랜덤 포레스트",
    "KNN & Distance Metrics": "KNN과 거리 지표",
    "Feature Engineering & Selection": "특성 공학과 선택",
    "Model Evaluation: Metrics, Cross-Validation": "모델 평가: 지표와 교차검증",
    "Bias, Variance & the Learning Curve": "편향, 분산과 학습 곡선",
    "Ensemble Methods: Boosting, Bagging, Stacking": "앙상블: Boosting, Bagging, Stacking",
    "ML Pipelines & Experiment Tracking": "ML 파이프라인과 실험 추적",
}


def existing_korean_titles():
    titles = {}
    for doc in ROOT.glob("phases/**/docs/ko.md"):
        first = doc.read_text(encoding="utf-8").splitlines()[0].removeprefix("# ").strip()
        first = re.sub(r"\s*\([^()]*[A-Za-z][^()]*\)\s*$", "", first).strip()
        lesson_path = doc.parent.parent.relative_to(ROOT).as_posix()
        titles[lesson_path] = first
    return titles


def structural_rewrite(name):
    # X for Y -> Y를 위한 X (simple two-part titles)
    m = re.match(r"^(.+?) for (.+)$", name)
    if m and ":" not in m.group(1) and len(m.group(2).split()) <= 4:
        return f"{m.group(2)}를 위한 {m.group(1)}"
    m = re.match(r"^(.+?) with (.+)$", name)
    if m and ":" not in m.group(1) and len(m.group(2).split()) <= 6:
        return f"{m.group(2)} 활용 {m.group(1)}"
    m = re.match(r"^Introduction to (.+)$", name)
    if m:
        return f"{m.group(1)} 입문"
    return name


def translate(name):
    if name in EXACT:
        return EXACT[name]

    title = structural_rewrite(name)
    for english, korean in sorted(PHRASES.items(), key=lambda item: len(item[0]), reverse=True):
        title = title.replace(english, korean)
    for english, korean in sorted(WORDS.items(), key=lambda item: len(item[0]), reverse=True):
        title = re.sub(rf"(?<![A-Za-z]){re.escape(english)}(?![A-Za-z])", korean, title)

    title = re.sub(r"\s+", " ", title)
    title = re.sub(r"\s+([,:)])", r"\1", title)
    title = re.sub(r"([(])\s+", r"\1", title)
    title = re.sub(r"\s*및\s*$", "", title)
    return title.strip(" -—:")


lessons = load_lessons()
existing = existing_korean_titles()
mapping = {lesson["path"]: existing.get(lesson["path"], translate(lesson["name"])) for lesson in lessons}

lines = [
    "// Korean lesson title map for catalog (path -> title)",
    "(function (root) {",
    "  'use strict';",
    "  root.AIFS_LESSON_TITLES_KO = {",
]
for index, (path, title) in enumerate(mapping.items()):
    comma = "," if index < len(mapping) - 1 else ""
    lines.append(f"    {json.dumps(path, ensure_ascii=False)}: {json.dumps(title, ensure_ascii=False)}{comma}")
lines.extend([
    "  };",
    "})(typeof window !== 'undefined' ? window : this);",
    "",
])
OUTPUT.write_text("\n".join(lines), encoding="utf-8")
print(f"wrote {len(mapping)} titles -> {OUTPUT}")
